import { ArrowRight, Download, History, Printer, Search } from 'lucide-react'
import { useState } from 'react'

import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { AdminPageError, AdminPageHeader, AdminPageSkeleton, EmptyPanel } from '@/features/admin/components/admin-shared'
import { formatDate, humanize } from '@/features/admin/data/admin-formatters'
import { useAdminResource, type AdminActivityResponse, type AdminAssessment, type AdminOverview, type AdminReport, type AdminStudentDirectory, type AdminStudentRecord } from '@/features/admin/data/admin-api'

interface NavigateProps { onNavigate: (path: string) => void }

function AdminDashboardPage({ onNavigate }: NavigateProps) {
  const resource = useAdminResource<AdminOverview>('/overview')
  const activity = useAdminResource<AdminActivityResponse>('/activity?perPage=5')
  if (resource.loading) return <AdminPageSkeleton />
  if (resource.error || !resource.data) return <AdminPageError message={resource.error ?? 'No dashboard data was returned.'} onRetry={resource.retry} />
  const data = resource.data
  const funnel = [
    ['Registered', data.funnel.registered], ['Entrance declared', data.funnel.entranceDeclared],
    ['Assessment started', data.funnel.assessmentStarted], ['In progress', data.funnel.inProgress],
    ['Processing', data.funnel.processing], ['Result available', data.funnel.resultAvailable],
  ] as const
  return <div className="mx-auto w-full max-w-[1500px] space-y-6">
    <AdminPageHeader eyebrow="Administrator operations" title="System overview" description="Monitor the Student journey, resolve operational exceptions, and govern programme evidence from authoritative records." action={<Button onClick={() => onNavigate('/admin/students')}>Open student directory <ArrowRight /></Button>} />
    <section className="rounded-3xl border border-border bg-card p-6 shadow-xs" aria-labelledby="funnel-heading">
      <p className="font-label text-sm font-bold uppercase tracking-wider text-primary">Current Student journey</p>
      <h2 id="funnel-heading" className="mt-1 font-display text-3xl font-extrabold">Assessment funnel</h2>
      <ol className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{funnel.map(([label, value], index) => <li key={label} className="rounded-2xl bg-secondary/70 p-4"><span className="font-label text-sm font-bold text-muted-foreground">{index + 1}. {label}</span><strong className="mt-2 block font-display text-3xl font-extrabold">{value}</strong></li>)}</ol>
    </section>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.6fr)_minmax(20rem,.7fr)]">
      <section className="rounded-3xl border border-border bg-card p-6 shadow-xs" aria-labelledby="recent-heading">
        <div className="flex items-center justify-between gap-4"><div><p className="font-label text-sm font-bold uppercase tracking-wider text-muted-foreground">Evidence timeline</p><h2 id="recent-heading" className="font-display text-2xl font-bold">Recent assessment activity</h2></div><Button variant="outline" onClick={() => onNavigate('/admin/students')}>View all</Button></div>
        {data.recentActivity.length ? <div className="mt-4 divide-y divide-border">{data.recentActivity.map((item) => <button key={item.id} type="button" onClick={() => onNavigate(`/admin/students/${item.studentId}`)} className="flex min-h-16 w-full items-center justify-between gap-4 py-3 text-left"><span><strong className="block text-base">{item.studentName}</strong><span className="font-label text-sm text-muted-foreground">Attempt {item.attemptNumber} · {formatDate(item.resultAvailableAt ?? item.submittedAt)}</span></span><span className="flex items-center gap-3"><StatusBadge status={item.status} />{item.topCode ? <Badge>{item.topCode}</Badge> : null}<ArrowRight className="size-4" /></span></button>)}</div> : <EmptyPanel title="No recent activity" description="Assessment activity will appear here." />}
      </section>
      <aside className="space-y-6">
        <section className="rounded-3xl border border-border bg-card p-6 shadow-xs" aria-labelledby="attention-heading"><h2 id="attention-heading" className="font-display text-2xl font-bold">Action queues</h2><p className="mt-1 text-base text-muted-foreground">Records needing Administrator attention.</p><div className="mt-4 divide-y divide-border"><QueueRow label="Processing failures" value={data.operationalAttention.processingFailures} onClick={() => onNavigate('/admin/students')} /><QueueRow label="Sources awaiting verification" value={data.operationalAttention.unverifiedSources} onClick={() => onNavigate('/admin/programmes/sources')} /><QueueRow label="Unpublished drafts" value={data.operationalAttention.unpublishedDrafts} onClick={() => onNavigate('/admin/programmes')} /></div></section>
        <section className="rounded-3xl border border-border bg-card p-6 shadow-xs"><div className="flex items-center justify-between"><h2 className="font-display text-xl font-bold">Admin activity</h2><Button variant="ghost" onClick={() => onNavigate('/admin/activity')}>View all</Button></div>{activity.data?.items.length ? <ol className="mt-3 divide-y divide-border">{activity.data.items.map((event) => <li key={event.id} className="py-3"><strong className="block text-sm">{event.summary}</strong><span className="font-label text-xs text-muted-foreground">{event.actor ?? 'Unknown Administrator'} · {formatDate(event.createdAt)}</span></li>)}</ol> : <p className="mt-3 text-sm text-muted-foreground">No recorded activity.</p>}</section>
      </aside>
    </div>
  </div>
}

function QueueRow({ label, value, onClick }: { label: string; value: number; onClick: () => void }) { return <button type="button" onClick={onClick} className="flex min-h-12 w-full items-center justify-between py-2 text-left text-base font-semibold"><span>{label}</span><Badge variant={value ? 'warning' : 'success'}>{value}</Badge></button> }

function AdminStudentsPage({ onNavigate }: NavigateProps) {
  const [query, setQuery] = useState(''); const [applied, setApplied] = useState(''); const [status, setStatus] = useState('all'); const [eligibility, setEligibility] = useState('all'); const [sort, setSort] = useState('last_activity'); const [page, setPage] = useState(1)
  const params = new URLSearchParams({ page: String(page), perPage: '20', sort, direction: sort === 'name' ? 'asc' : 'desc' })
  if (applied) params.set('search', applied); if (status !== 'all') params.set('status', status); if (eligibility !== 'all') params.set('eligibility', eligibility)
  const resource = useAdminResource<AdminStudentDirectory>(`/students?${params}`)
  if (resource.loading) return <AdminPageSkeleton />
  if (resource.error || !resource.data) return <AdminPageError message={resource.error ?? 'No student monitoring data was returned.'} onRetry={resource.retry} />
  const data = resource.data
  return <div className="min-w-0 space-y-6">
    <AdminPageHeader eyebrow="Student and assessment monitoring" title="Student records" description="Search authoritative Student journey records and open immutable attempt evidence." />
    <section className="min-w-0 rounded-3xl border border-border bg-card p-4 shadow-xs sm:p-6" data-student-records>
      <form className="grid gap-3 md:grid-cols-2 xl:grid-cols-[minmax(16rem,1fr)_13rem_13rem_12rem_auto]" onSubmit={(event) => { event.preventDefault(); setPage(1); setApplied(query.trim()) }}>
        <label className="relative md:col-span-2 xl:col-span-1"><span className="sr-only">Search student records</span><Search className="absolute left-3.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Name, email, reference, or RIASEC" className="pl-10" /></label>
        <FilterSelect label="Filter by assessment status" value={status} onChange={(value) => { setStatus(value); setPage(1) }} options={[['all','All statuses'],['not_started','Not started'],['in_progress','In progress'],['preparing_result','Processing'],['result_available','Result available'],['result_failed','Needs attention']]} />
        <FilterSelect label="Filter by eligibility group" value={eligibility} onChange={(value) => { setEligibility(value); setPage(1) }} options={[['all','All eligibility'],['board','Board eligible'],['non_board','Non-board eligible'],['not_declared','Not declared']]} />
        <FilterSelect label="Sort student records" value={sort} onChange={(value) => { setSort(value); setPage(1) }} options={[['last_activity','Recent activity'],['name','Student name'],['attempt_count','Attempt count']]} />
        <Button type="submit">Search</Button>
      </form>
      {data.items.length ? <ul className="mt-6 space-y-3 sm:hidden">{data.items.map((student) => <li key={student.id} className="rounded-2xl border border-border bg-secondary/35 p-4"><div className="flex items-start justify-between gap-3"><div><strong className="block text-base">{student.name}</strong><span className="font-label text-xs text-muted-foreground">{student.email}</span></div>{student.currentAssessmentStatus === 'not_started' ? <Badge variant="secondary">Not started</Badge> : <StatusBadge status={student.currentAssessmentStatus} />}</div><dl className="mt-4 grid grid-cols-2 gap-3"><Evidence label="Entrance" value={student.declarationStatus === 'declared' ? `${student.selfDeclaredScore} · ${humanize(student.eligibilityGroup ?? '')}` : 'Not declared'} /><Evidence label="Latest RIASEC" value={student.latestTopCode ?? 'Pending'} /><Evidence label="Attempts" value={String(student.attemptCount)} /><Evidence label="Saved programmes" value={String(student.savedProgrammeCount)} /></dl><Button className="mt-4 w-full" variant="outline" onClick={() => onNavigate(`/admin/students/${student.id}`)}>Open <ArrowRight /></Button></li>)}</ul> : null}
      {data.items.length ? <div className="mt-6 overflow-x-auto rounded-2xl border border-border"><table className="w-full min-w-[88rem] text-left text-sm"><thead className="bg-secondary font-label text-xs uppercase tracking-wider text-muted-foreground"><tr><th className="p-4">Student</th><th className="p-4">Entrance declaration</th><th className="p-4">Assessment</th><th className="p-4">Attempts</th><th className="p-4">RIASEC</th><th className="p-4">Recommendation</th><th className="p-4">Saved</th><th className="p-4">Last activity</th><th className="p-4"><span className="sr-only">Action</span></th></tr></thead><tbody className="divide-y divide-border">{data.items.map((student) => <tr key={student.id} className="hover:bg-secondary/40"><td className="p-4"><strong className="block text-base">{student.name}</strong><span className="font-label text-xs text-muted-foreground">{student.email}</span></td><td className="p-4">{student.declarationStatus === 'declared' ? <><strong className="block">{student.selfDeclaredScore}</strong><span className="font-label text-xs text-muted-foreground">{humanize(student.eligibilityGroup ?? '')}</span></> : <Badge variant="secondary">Not declared</Badge>}</td><td className="p-4">{student.currentAssessmentStatus === 'not_started' ? <Badge variant="secondary">Not started</Badge> : <><StatusBadge status={student.currentAssessmentStatus} /><span className="mt-1 block font-label text-xs text-muted-foreground">{student.currentAssessmentReference}</span></>}</td><td className="p-4 font-bold">{student.attemptCount}</td><td className="p-4">{student.latestTopCode ? <Badge>{student.latestTopCode}</Badge> : '—'}</td><td className="p-4"><Badge variant={student.recommendationAvailable ? 'success' : 'secondary'}>{student.recommendationAvailable ? 'Available' : 'Pending'}</Badge></td><td className="p-4 font-bold">{student.savedProgrammeCount}</td><td className="p-4 font-label text-xs text-muted-foreground">{formatDate(student.lastActivityAt)}</td><td className="p-4"><Button variant="ghost" onClick={() => onNavigate(`/admin/students/${student.id}`)}>Open <ArrowRight /></Button></td></tr>)}</tbody></table></div> : <div className="mt-6"><EmptyPanel title="No student records match" description="Change the search or filters." /></div>}
      <div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="font-label text-sm text-muted-foreground">Showing {data.pagination.from ?? 0}–{data.pagination.to ?? 0} of {data.pagination.total} records.</p><div className="flex gap-2"><Button variant="outline" disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</Button><Button variant="outline" disabled={page >= data.pagination.lastPage} onClick={() => setPage(page + 1)}>Next</Button></div></div>
    </section>
  </div>
}

function FilterSelect({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: Array<[string,string]> }) { return <label><span className="sr-only">{label}</span><select aria-label={label} value={value} onChange={(event) => onChange(event.target.value)} className="min-h-11 w-full rounded-xl border border-input bg-background px-3 font-label text-sm font-semibold">{options.map(([option,labelText]) => <option key={option} value={option}>{labelText}</option>)}</select></label> }

function AdminStudentDetailPage({ studentId, onNavigate }: { studentId: string; onNavigate: (path: string) => void }) {
  const resource = useAdminResource<AdminStudentRecord>(`/students/${studentId}`)
  if (resource.loading) return <AdminPageSkeleton />
  if (resource.error || !resource.data) return <AdminPageError message={resource.error ?? 'No student record was returned.'} onRetry={resource.retry} />
  const student = resource.data
  return <div className="space-y-6" data-report-print>
    <AdminPageHeader eyebrow="Immutable evidence timeline" title={student.name} description={`${student.email} · ${student.attempts.length} recorded attempts · ${student.savedProgrammeCount} saved programmes`} action={<Button variant="outline" onClick={() => onNavigate('/admin/students')}>Back to students</Button>} />
    {student.attempts.length ? <ol className="relative space-y-6 border-l-2 border-primary/25 pl-6">{student.attempts.map((attempt) => <li key={attempt.id} className="relative"><span className="absolute -left-[1.95rem] top-6 size-3 rounded-full bg-primary ring-4 ring-background" /><article className="rounded-3xl border border-border bg-card p-6 shadow-xs"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-label text-sm font-bold uppercase tracking-wider text-primary">Attempt {attempt.attemptNumber}</p><h2 className="mt-1 font-display text-2xl font-extrabold">{attempt.topCode ? `${attempt.topCode} interest profile` : 'Assessment evidence'}</h2><p className="mt-1 font-label text-sm text-muted-foreground">{attempt.reference} · {attempt.instrumentCode}</p></div><StatusBadge status={attempt.status} /></div>
      <dl className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Evidence label="Entrance result" value={attempt.entranceExamination ? `${attempt.entranceExamination.score} · ${humanize(attempt.entranceExamination.eligibilityGroup)}` : 'Not captured'} /><Evidence label="Admission rule" value={attempt.entranceExamination?.ruleReference ?? 'Not captured'} /><Evidence label="Instrument progress" value={`${attempt.answerCount} of ${attempt.questionCount} answers`} /><Evidence label="Lifecycle" value={`${formatDate(attempt.startedAt)} → ${formatDate(attempt.resultAvailableAt ?? attempt.processingFailedAt ?? attempt.submittedAt)}`} /></dl>
      {attempt.dimensions?.length ? <div className="mt-5"><h3 className="font-display text-xl font-bold">Exact RIASEC raw scores</h3><dl className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-6">{attempt.dimensions.map((dimension) => <div key={dimension.code} className="rounded-2xl bg-secondary p-4 text-center"><dt className="font-label text-sm font-bold">{dimension.code} · {dimension.label}</dt><dd className="font-display text-2xl font-extrabold text-primary">{dimension.value}</dd></div>)}</dl></div> : null}
      <dl className="mt-5 grid gap-3 sm:grid-cols-2"><Evidence label="Recommendation snapshot" value={attempt.recommendationSnapshot ? `${attempt.recommendationSnapshot.catalogueReference} · ${attempt.recommendationSnapshot.ruleReference} · ${attempt.recommendationSnapshot.methodologyStatus}` : 'Not generated'} /><Evidence label="Failure or retake context" value={attempt.processingErrorCode ?? attempt.retakeReason ?? 'None recorded'} /></dl>
      {attempt.recommendations?.length ? <div className="mt-5"><h3 className="font-display text-xl font-bold">Ranked programme snapshot</h3><ol className="mt-3 grid gap-3 lg:grid-cols-3">{attempt.recommendations.map((programme) => <li key={programme.id} className="rounded-2xl border border-border p-4"><span className="font-label text-sm font-bold text-muted-foreground">#{programme.rank} · {programme.code}</span><strong className="mt-2 block text-base">{programme.name}</strong><span className="font-display text-lg font-extrabold text-primary">{programme.match}% match</span></li>)}</ol></div> : null}
    </article></li>)}</ol> : <EmptyPanel title="No assessment attempts" description="This student has not started an assessment." />}
  </div>
}

function Evidence({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-secondary/70 p-4"><dt className="font-label text-xs font-bold uppercase tracking-wider text-muted-foreground">{label}</dt><dd className="mt-1 break-words text-base font-semibold">{value}</dd></div> }

function AdminReportsPage() {
  const [from,setFrom] = useState(''); const [to,setTo] = useState(''); const [query,setQuery] = useState('')
  const resource = useAdminResource<AdminReport>(`/reports${query}`)
  if (resource.loading) return <AdminPageSkeleton />
  if (resource.error || !resource.data) return <AdminPageError message={resource.error ?? 'No report data was returned.'} onRetry={resource.retry} />
  const data = resource.data; const invalid = Boolean(from && to && to < from); const exportQuery = query
  const metrics = [['Entrance declarations',data.entranceDeclarations],['Board eligible',data.eligibilityDistribution.board],['Non-board eligible',data.eligibilityDistribution.nonBoard],['Recommendation runs',data.recommendationRuns],['Programme saves',data.programmeSaves],['Processing failures',data.assessmentFunnel.failed]] as const
  return <div className="space-y-6" data-report-print><AdminPageHeader eyebrow="Privacy-safe aggregate records" title="System reports" description="Monitor the Student funnel, recommendations, programme saves, and catalogue governance without identifiable exports." action={<div className="flex gap-2"><Button variant="outline" onClick={() => window.print()}><Printer /> Print</Button><Button onClick={() => { window.location.href = `/api/v1/admin/reports/export${exportQuery}` }}><Download /> Export aggregate CSV</Button></div>} />
    <section className="rounded-3xl border border-border bg-card p-6 shadow-xs"><form className="grid gap-3 sm:grid-cols-[1fr_1fr_auto_auto]" onSubmit={(event) => { event.preventDefault(); if (!invalid) setQuery(from || to ? `?${new URLSearchParams({...(from?{from}:{}),...(to?{to}:{})})}` : '') }}><label className="font-label text-sm font-bold">From<Input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label className="font-label text-sm font-bold">To<Input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label><Button type="submit" disabled={invalid}>Apply dates</Button><Button type="button" variant="ghost" onClick={() => { setFrom(''); setTo(''); setQuery('') }}>Clear</Button></form>{invalid ? <p role="alert" className="mt-2 text-sm text-destructive">The end date must be on or after the start date.</p> : null}</section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{metrics.map(([label,value]) => <ReportMetric key={label} label={label} value={value} />)}</section>
    <div className="grid gap-6 xl:grid-cols-2"><ReportPanel title="Assessment funnel"><Stat label="Started" value={data.assessmentFunnel.started} /><Stat label="In progress" value={data.assessmentFunnel.inProgress} /><Stat label="Processing" value={data.assessmentFunnel.processing} /><Stat label="Results available" value={data.assessmentFunnel.resultAvailable} /></ReportPanel><ReportPanel title="Programme engagement"><Stat label="Board recommendation runs" value={data.recommendationsByEligibility.board} /><Stat label="Non-board recommendation runs" value={data.recommendationsByEligibility.nonBoard} /><Stat label="Board programme saves" value={data.programmeSavesByEligibility.board} /><Stat label="Non-board programme saves" value={data.programmeSavesByEligibility.nonBoard} /></ReportPanel><ReportPanel title="Catalogue and source governance"><Stat label="Current sources" value={data.catalogueGovernance.currentSources} /><Stat label="Review due" value={data.catalogueGovernance.reviewDueSources} /><Stat label="Unverified" value={data.catalogueGovernance.unverifiedSources} /><Stat label="Draft versions" value={data.catalogueGovernance.draftVersions} /></ReportPanel><ReportPanel title="Completion"><Stat label="Completed assessments" value={data.completedAssessments} /><Stat label="Completion rate" value={`${data.assessmentCompletionRate}%`} /><Stat label="Students in scope" value={data.studentCount} /><Stat label="Assessment activity" value={data.assessmentActivity} /></ReportPanel></div>
    <p className="font-label text-sm text-muted-foreground">Generated {formatDate(data.generatedAt)}. Aggregate counts only; identifiable exports remain disabled.</p>
  </div>
}

function ReportPanel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-3xl border border-border bg-card p-6 shadow-xs"><h2 className="font-display text-2xl font-bold">{title}</h2><dl className="mt-4 divide-y divide-border">{children}</dl></section> }
function Stat({ label, value }: { label: string; value: string | number }) { return <div className="flex items-center justify-between py-3"><dt className="text-base text-muted-foreground">{label}</dt><dd className="font-display text-xl font-extrabold">{value}</dd></div> }
function ReportMetric({ label, value }: { label: string; value: number }) { return <article className="rounded-3xl border border-border bg-card p-5 shadow-xs"><p className="font-label text-sm font-bold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-2 font-display text-4xl font-extrabold">{value}</p></article> }

function AdminActivityPage() {
  const [actor,setActor] = useState(''); const [action,setAction] = useState(''); const [subject,setSubject] = useState(''); const [from,setFrom] = useState(''); const [to,setTo] = useState(''); const [page,setPage] = useState(1)
  const params = new URLSearchParams({ page: String(page), perPage: '25' }); if (actor) params.set('actor',actor); if (action) params.set('action',action); if (subject) params.set('subjectType',subject); if (from) params.set('from',from); if (to) params.set('to',to)
  const resource = useAdminResource<AdminActivityResponse>(`/activity?${params}`)
  if (resource.loading) return <AdminPageSkeleton />
  if (resource.error || !resource.data) return <AdminPageError message={resource.error ?? 'No activity data was returned.'} onRetry={resource.retry} />
  const data = resource.data
  return <div className="space-y-6"><AdminPageHeader eyebrow="Individual-account accountability" title="Admin activity" description="Filter auditable actions by Administrator, action, record type, and date. Entries show safe version and change summaries." />
    <section className="rounded-3xl border border-border bg-card p-6 shadow-xs"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><FilterSelect label="Administrator" value={actor} onChange={(value) => { setActor(value); setPage(1) }} options={[['','All Administrators'],...data.filters.actors.map((item) => [String(item.id),item.name] as [string,string])]} /><FilterSelect label="Action" value={action} onChange={(value) => { setAction(value); setPage(1) }} options={[['','All actions'],...data.filters.actions.map((item) => [item,humanize(item)] as [string,string])]} /><FilterSelect label="Record type" value={subject} onChange={(value) => { setSubject(value); setPage(1) }} options={[['','All record types'],...data.filters.subjectTypes.map((item) => [item,humanize(item)] as [string,string])]} /><Input aria-label="Activity from date" type="date" value={from} onChange={(event) => { setFrom(event.target.value); setPage(1) }} /><Input aria-label="Activity to date" type="date" value={to} onChange={(event) => { setTo(event.target.value); setPage(1) }} /></div></section>
    {data.items.length ? <section className="rounded-3xl border border-border bg-card p-6 shadow-xs"><ol className="divide-y divide-border">{data.items.map((event) => <li key={event.id} className="grid gap-3 py-4 sm:grid-cols-[2.5rem_minmax(0,1fr)_auto]"><span className="flex size-10 items-center justify-center rounded-2xl bg-secondary text-primary"><History className="size-5" /></span><span><strong className="block text-base">{event.summary}</strong><span className="font-label text-sm text-muted-foreground">{event.actor ?? 'Unknown Administrator'} · {humanize(event.subjectType)} {event.subjectReference}</span>{event.metadata && Object.keys(event.metadata).length ? <span className="mt-1 block font-label text-xs text-muted-foreground">{Object.entries(event.metadata).map(([key,value]) => `${humanize(key)}: ${String(value)}`).join(' · ')}</span> : null}</span><time className="font-label text-xs text-muted-foreground">{formatDate(event.createdAt)}</time></li>)}</ol><div className="mt-4 flex justify-end gap-2"><Button variant="outline" disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</Button><Button variant="outline" disabled={page >= data.pagination.lastPage} onClick={() => setPage(page + 1)}>Next</Button></div></section> : <EmptyPanel title="No recorded activity" description="Change the filters or wait for an auditable action." />}
  </div>
}

function StatusBadge({ status }: { status: AdminAssessment['status'] }) { const variants = { in_progress: 'warning', preparing_result: 'info', result_available: 'success', result_failed: 'destructive' } as const; const labels = { in_progress: 'In progress', preparing_result: 'Processing', result_available: 'Result available', result_failed: 'Needs attention' }; return <Badge variant={variants[status]}>{labels[status]}</Badge> }

export { AdminActivityPage, AdminDashboardPage, AdminReportsPage, AdminStudentDetailPage, AdminStudentsPage }
